### ISSUE TITLE
Dedicated plotting

### ISSUE THREAD

**Issue by smartalecH** [hammy4815/VectorModesolver#1]
Might be nice to have a dedicated visualization routine (using `Makie`). Something like

```julia

function plot_mode_fields(mode_data::Mode; kwargs...)
# 2x3 subplots of the fields overlaying the geometry
# style can be modified using kwargs
end

```

**Comment by ianmatthewhammond** [comment]
It's a good idea. I was planning to implement plotting and a few other routines (Overlap / Power, polarization prediction, etc.) once the code is fully working.

**Comment by ianmatthewhammond** [comment]
I'll just keep this here for now and people can add suggestions to the thread

General ToDo

1. Include tests
2. Include stretched / complex coordinates for PML
3. Multithread the main for loops of assemble
4. Add Poynting vector, intensity, overlap integrals, etc. functionality to normalize fields and other applications
5. Add visualization functionality (plot Ex, Ey, Ez, Hx, Hy, Hz, Px, Py, Pz, I, Eps)
6. TE/TM fractions
7. Inner products / Overlaps between two different fields for computing mode coefficients
8. Export to file functionality
9. Write up example scripts / short documentation

**Comment by smartalecH** [comment]
I would refactor the above into separate issues with tags etc so they can be individually tracked and closed.
